basePath: '{{.BasePath}}'
definitions:
  model.TeamSerializer:
    properties:
      area:
        type: string
      city:
        type: string
      create_at:
        type: string
      delete_at:
        type: string
      id:
        type: integer
      logo:
        type: string
      name:
        type: string
      subarea:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /v1/team/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TeamSerializer'
            type: object
      summary: get Team by id
      tags:
      - Team
  /v1/teams:
    get:
      consumes:
      - application/json
      parameters:
      - description: area
        in: query
        name: area
        type: string
      - description: subarea
        in: query
        name: subarea
        type: string
      - description: name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TeamSerializer'
            type: array
      summary: query Team by something
      tags:
      - Team
swagger: "2.0"
